export default [
  {
    regionCode: '1',
    division: 'Ayeyarwady Region',
    townshipCodes: [
      'Hinthada',
      'Kyangin',
      'Labutta',
      'Maubin',
      'Myaungmya',
      'Pathein',
      'Pyapon',
      'Bogale',
      'Myanaung',
    ],
  },
  {
    regionCode: '2',
    division: 'Bago Region',
    townshipCodes: [
      'Bago',
      'Nyaunglebin',
      'Pyay',
      'Tharrawaddy',
      'Taungoo',
      'Nattalin',
    ],
  },
  {
    regionCode: '3',
    division: 'Chin State',
    townshipCodes: [
      'Falam',
      'Hakha',
      'Matupi',
      'Mindat',
      'Paletwa',
      'Tedim',
    ],
  },
  {
    regionCode: '4',
    division: 'Kachin State',
    townshipCodes: [
      'Bhamo',
      'Chipwi',
      'Mohnyin',
      'Myitkyina',
      'Putao',
      'Tanai',
    ],
  },
  {
    regionCode: '5',
    division: 'Kayah State',
    townshipCodes: [
      'Bawlakhe',
      'Demoso',
      'Loikaw',
      'Mese',
    ],
  },
  {
    regionCode: '6',
    division: 'Kayin State',
    townshipCodes: [
      'Hpa-an',
      'Hpapun',
      'Kawkareik',
      'Kyain Seikgyi',
      'Myawaddy',
      'Thandaunggyi',
    ],
  },
  {
    regionCode: '7',
    division: 'Magway Region',
    townshipCodes: [
      'Aunglan',
      'Chauk',
      'Gangaw',
      'Magway',
      'Minbu',
      'Pakokku',
      'Thayet',
      'Salin',
      'Taungdwingyi',
      'Yesagyo',
    ],
  },
  {
    regionCode: '8',
    division: 'Mandalay Region',
    townshipCodes: [
      'Amarapura',
      'Aungmyethazan',
      'Kyaukse',
      'Maha Aungmye',
      'Meiktila',
      'Myingyan',
      'Nyaung-U',
      'Pyin Oo Lwin',
      'Tada-U',
      'Thabeikkyin',
      'Yamethin',
    ],
  },
  {
    regionCode: '9',
    division: 'Mon State',
    townshipCodes: [
      'Kyaikto',
      'Mawlamyine',
      'Thaton',
      'Ye',
    ],
  },
  {
    regionCode: '10',
    division: 'Naypyidaw Union Territory',
    townshipCodes: [
      'Ottarathiri',
      'Zeyathiri',
      'Dekkhinathiri',
      'Pyinmana',
    ],
  },
  {
    regionCode: '11',
    division: 'Rakhine State',
    townshipCodes: [
      'Ann',
      'Kyaukpyu',
      'Maungdaw',
      'Mrauk-U',
      'Pauktaw',
      'Sittwe',
      'Thandwe',
      'Toungup',
    ],
  },
  {
    regionCode: '12',
    division: 'Sagaing Region',
    townshipCodes: [
      'Ayadaw',
      'Banmauk',
      'Budalin',
      'Chaung-U',
      'Homalin',
      'Kalewa',
      'Kani',
      'Katha',
      'Kawlin',
      'Khin-U',
      'Kyunhla',
      'Minkin',
      'Monywa',
      'Myinmu',
      'Paungbyin',
      'Pinlebu',
      'Sagaing',
      'Shwebo',
      'Tabayin',
      'Tamu',
      'Taze',
      'Wuntho',
      'Yinmabin',
    ],
  },
  {
    regionCode: '13',
    division: 'Shan State',
    townshipCodes: [
      'Kengtung',
      'Mong Hsat',
      'Mong Hpayak',
      'Mong Kyawt',
      'Mong Nawng',
      'Mong Pan',
      'Mong Ping',
      'Mong Ton',
      'Mong Yawng',
      'Namhsan',
      'Nansang',
      'Pekon',
      'Tachileik',
      'Taunggyi',
      'Hopang',
    ],
  },
  {
    regionCode: '14',
    division: 'Tanintharyi Region',
    townshipCodes: [
      'Dawei',
      'Kawthaung',
      'Launglon',
      'Myeik',
      'Palaw',
      'Tanintharyi',
      'Thayetchaung',
    ],
  },
  {
    regionCode: '15',
    division: 'Yangon Region',
    townshipCodes: [
      'Dagon',
      'Insein',
      'Kyauktada',
      'Pabedan',
      'Bahan',
      'Hlaing',
      'Kamayut',
      'Latha',
      'Mayangone',
      'Sanchaung',
      'Shwepyitha',
      'South Okkalapa',
      'North Okkalapa',
      'Thingangyun',
      'Thaketa',
      'Tamwe',
      'Dala',
    ],
  },
];
